default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1 # ← ここを追加（IPv4でつなぐ）
  username: postgres # ← ここを追加（Postgresのユーザー名）
  password: kaiyu0208 # ← ここを追加（Postgresのパスワード）
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sharehouse_development

test:
  <<: *default
  database: sharehouse_test

production:
  primary: &primary_production
    <<: *default
    database: sharehouse_production
  cache:
    <<: *primary_production
    database: sharehouse_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sharehouse_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sharehouse_production_cable
    migrations_paths: db/cable_migrate
